name: Fernando Rosa
description: O mar arremessa as rochas, mas o tempo nos deixa pedras lapidadas
meta_description: "Fernando Rosa, Chapecó SC"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 'https://nandomegaman.github.io'
domain_name: 'https://nandomegaman.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://nandomegaman.github.io'
author:         'Fernando Rosa'
