name: Fernando Rosa
description: O mar arremessa as rochas, mas o tempo nos deixa pedras lapidadas.
meta_description: "Fernando Rosa, Chapecó SC"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Fernando Rosa'
